# ----------------------
#
#	SpaceProject - Bun Runner
#
# ----------------------

FROM --platform=$TARGETOS/$TARGETARCH node:18-alpine

# Install dependencies
RUN apk add --no-cache \
	bash \
	curl \
	git \
	openssh-client \
	python3 \
	py3-pip \
	rsync \
	tar \
	unzip \
	wget \
	zip

# Install bun
RUN curl https://bun.sh/install | bash

RUN export BUN_INSTALL="$HOME/.bun" && export PATH="$BUN_INSTALL/bin:$PATH" 

# Set the working directory
WORKDIR /app

ENTRYPOINT [ "bun" ]
CMD [ "run" ]