# ----------------------
#
#	SpaceProject - Bun Runner
#
# ----------------------

FROM --platform=$TARGETOS/$TARGETARCH oven/bun:latest

# Install dependencies
RUN apk add --no-cache \
	bash \
	curl \
	git \
	openssh-client \
	python3 \
	py3-pip \
	rsync \
	tar \
	unzip \
	wget \
	zip

# Set the working directory
WORKDIR /app