# ----------------------
#
#	SpaceProject - Excalidraw
#
# ----------------------
FROM --platform=$TARGETOS/$TARGETARCH node:18-bullseye AS builder

LABEL author="GaryC" maintainer="garycraft@our-space.xyz"

WORKDIR /build

# Install git and jq
RUN apt-get update && \
	apt-get install -y git jq
# Clean up apt-get
RUN apt-get clean && \
	rm -rf /var/lib/apt/lists/*

# Get the Excalidraw source code
RUN git clone https://github.com/excalidraw/excalidraw

# Install the Excalidraw dependencies
RUN cd excalidraw && \
	yarn --ignore-optional --network-timeout 600000

ARG NODE_ENV=production

# Fix Some chunks are larger than 500 kBs after minification. using jq
RUN cd excalidraw && \
	jq '.build.chunkSizeWarningLimit = 1000000' package.json > package.json.tmp && \
	mv package.json.tmp package.json


# Build the Excalidraw app
RUN cd excalidraw && \
	yarn build

FROM --platform=$TARGETOS/$TARGETARCH nginx:1.21-alpine AS runner

LABEL author="GaryC" maintainer="garycraft@our-space.xyz"

COPY --from=builder /build/excalidraw/build /usr/share/nginx/html

HEALTHCHECK CMD wget --quiet --tries=1 http://localhost || exit 1