# ----------------------
#
#	SpaceProject - FastReverseProxy (frp)
#
# ----------------------
FROM --platform=$TARGETOS/$TARGETARCH golang:1.21 as builder

LABEL author="GaryC" maintainer="garycraft@our-space.xyz"

RUN apt-get update && apt-get install -y git

WORKDIR /build

# Get the frp source code
RUN git clone https://github.com/fatedier/frp

# And Build it
RUN cd frp && \
	make frps && \
	make frpc

FROM --platform=$TARGETOS/$TARGETARCH alpine:3.18 as runner

LABEL author="GaryC" maintainer="garycraft@our-space.xyz"

WORKDIR /storage

COPY --from=builder /build/frp/bin/frps /usr/local/bin/frps
COPY --from=builder /build/frp/bin/frpc /usr/local/bin/frpc

ENTRYPOINT [ "/usr/local/bin/frps" ]

CMD ["-c", "/storage/frps.ini"]