FROM ghcr.io/ropenttd/openttd:15.0-beta2
LABEL maintainer garycraft@our-space.xyz

ADD entrypoint.sh /usr/local/bin/entrypoint

RUN chown -R openttd:openttd /config /app
WORKDIR /home/container
ENV XDG_DATA_HOME=/home/container
ENV PATH="$PATH:/app"

USER openttd
CMD [ "/usr/local/bin/entrypoint" ]