# ----------------------
#
#	GaryCraft - TypeScript
#
# ----------------------

FROM ghcr.io/garycraft/yolks:node_universal

LABEL author="GaryCraft" maintainer="garycraft@our-space.xyz"

USER root
RUN apt update && apt install -y jq && rm -rf /var/lib/apt/lists/*

USER container
ENV USER=container HOME=/home/container
WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]