# ----------------------
#
#	GaryCraft - TypeScript
#
# ----------------------

FROM ghcr.io/garycraft/yolks:nodejs_universal

LABEL author="GaryCraft" maintainer="garycraft@our-space.xyz"

USER container
ENV USER=container HOME=/home/container
WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]