# ----------------------------------
# Pterodactyl ARM nodejs Dockerfile
# Environment: Alpine Linux 3.14.1
# Minimum Panel Version: 1.0.0
# ----------------------------------
FROM alpine:3.14.1

LABEL Author="GaryCraft@SpaceProject, <garycraft@our-space.xyz>"

RUN apk add --update nodejs npm

RUN apk add --no-cache --update curl ca-certificates openssl git tar bash python3 && ln -sf python3 /usr/bin/pytho

RUN adduser -D -h /home/container container

RUN node -v && npm -v

COPY ./entrypoint.sh /entrypoint.sh

RUN chmod +x entrypoint.sh

USER container
ENV  USER=container HOME=/home/container

WORKDIR /home/container



CMD ["/bin/sh", "/entrypoint.sh"]