# ----------------------
#
#	SpaceProject - Excalidraw Room
#
# ----------------------
FROM --platform=$TARGETOS/$TARGETARCH node:18-alpine

LABEL author="GaryC" maintainer="garycraft@our-space.xyz"

WORKDIR /excalidraw-room

# Get the Excalidraw Room source code
RUN git clone https://github.com/excalidraw/excalidraw-room

# Move package.json yarn.lock tsconfig.json and src to the working directory
RUN mv excalidraw-room/package.json excalidraw-room/yarn.lock excalidraw-room/tsconfig.json excalidraw-room/src ./
# Install yarn
RUN npm install -g yarn
# And the Excalidraw dependencies
RUN yarn

# Build the Excalidraw Room app
RUN yarn build

# ----------------------

CMD ["yarn", "start"]