# ----------------------
#
#	GaryCraft - TypeScript + Canvas
#
# ----------------------

FROM ghcr.io/garycraft/yolks:typescript

LABEL author="GaryCraft" maintainer="garycraft@our-space.xyz"

USER root
RUN apt update && apt -y install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
RUN npm install -g canvas

USER container
ENV USER=container HOME=/home/container
WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]