FROM        --platform=$TARGETOS/$TARGETARCH debian:bullseye-slim

LABEL       author="GaryC" maintainer="garycraft@our-space.xyz"

RUN         apt update \
	&& apt -y install ffmpeg iproute2 git sqlite3 libsqlite3-dev python3 python3-dev ca-certificates dnsutils tzdata zip tar curl build-essential libtool \
	&& useradd -m -d /home/container container

## Prepare nvm directory
RUN mkdir -p /usr/local/nvm && chown container:container /usr/local/nvm

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container
ENV 		NVM_DIR /usr/local/nvm
RUN git clone https://github.com/nvm-sh/nvm.git "$NVM_DIR" && cd "$NVM_DIR" && git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)` && \. "$NVM_DIR/nvm.sh"

COPY        ./entrypoint.sh /entrypoint.sh
CMD         [ "/bin/bash", "/entrypoint.sh" ]