# ----------------------
#
#	SpaceProject - CodeServer
#
# ----------------------

## Reference from https://github.com/linuxserver/docker-code-server

FROM --platform=$TARGETOS/$TARGETARCH ubuntu:22.04

LABEL author="GaryC" maintainer="garycraft@our-space.xyz"

# environment settings
ARG DEBIAN_FRONTEND="noninteractive"
ENV HOME="/config"

# Install runtime dependencies
RUN apt-get update && \
	apt-get install -y \
	curl \
	wget \
	git \
	jq \
	libatomic1 \
	nano \
	net-tools \
	netcat

# Install code-server
RUN CODE_RELEASE=$(curl -s https://api.github.com/repos/coder/code-server/releases/latest \
	| jq --arg TARGETARCH "$TARGETARCH" -r '.assets[] | select(.name | contains($TARGETARCH)) | .browser_download_url' \
	| awk -F/ '{print $NF}' | sed 's/^code-server-//' | sed 's/-linux.*gz$//') && \
	CODE_DOWNLOAD_URL=https://github.com/coder/code-server/releases/download/v${CODE_RELEASE}/code-server-${CODE_RELEASE}-linux-$TARGETARCH.tar.gz && \
	echo "Downloading code-server from ${CODE_DOWNLOAD_URL}" && \
	echo "Using Code-Release ${CODE_RELEASE}" && \
	wget -qO- ${CODE_DOWNLOAD_URL} \
	| tar xz -C /app/code-server --strip-components=1
# Install Node 16
RUN \
	echo "**** install Node 16 ****" && \
		curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - && \
		apt-get install -y nodejs
# Install php 8.2 and composer
RUN \
	echo "**** install php 8.2 and composer ****" && \
		apt-get update && \
		apt-get install -y \
		php8.2 \
		php8.2-cli \
		php8.2-common \
		php8.2-curl \
		php8.2-fpm \
		php8.2-gd \
		php8.2-json \
		php8.2-mbstring \
		php8.2-mysql \
		php8.2-opcache \
		php8.2-readline \
		php8.2-xml \
		php8.2-zip && \
		curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php && \
		php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
RUN	\
	echo "**** clean up ****" && \
		apt-get clean && \
		rm -rf \
		/config/* \
		/tmp/* \
		/var/lib/apt/lists/* \
		/var/tmp/*

# add local files (get from original repo)
#COPY /root /
# https://github.com/linuxserver/docker-code-server/tree/master/root
RUN \
	git clone https://github.com/linuxserver/docker-code-server --depth 1 && \
	cp -r /docker-code-server/root/* / && \
	rm -rf /docker-code-server


# ports and volumes
EXPOSE 8443