# ----------------------
#
#	SpaceProject - CodeServer
#
# ----------------------

## Reference from https://github.com/linuxserver/docker-code-server

FROM --platform=$TARGETOS/$TARGETARCH ubuntu:22.04

LABEL author="GaryC" maintainer="garycraft@our-space.xyz"

# environment settings
ARG DEBIAN_FRONTEND="noninteractive"
ENV HOME="/config"

# Get CodeServer
RUN \
	echo "**** install runtime dependencies ****" && \
		apt-get update && \
		apt-get install -y \
		git \
		jq \
		libatomic1 \
		nano \
		net-tools \
		netcat \
		sudo && \
		echo "**** install code-server ****" && \
		CODE_RELEASE=$(curl -sX GET https://api.github.com/repos/coder/code-server/releases/latest \
		| jq --arg TARGETARCH "$TARGETARCH" -r '.assets[] | select(.name | contains($TARGETARCH)) | .browser_download_url' \
		| awk -F/ '{print $NF}' | sed 's/^code-server-//' | sed 's/-linux.*gz$//') && \
		mkdir -p /app/code-server && \
		curl -o \
		/tmp/code-server.tar.gz -L \
		"https://github.com/coder/code-server/releases/download/v${CODE_RELEASE}/code-server-${CODE_RELEASE}-linux-$TARGETARCH.tar.gz" && \
		tar xf /tmp/code-server.tar.gz -C \
		/app/code-server --strip-components=1 && \
		echo "**** clean up ****" && \
		apt-get clean && \
		rm -rf \
		/config/* \
		/tmp/* \
		/var/lib/apt/lists/* \
		/var/tmp/*
# Install Node 16
RUN \
	echo "**** install Node 16 ****" && \
		curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - && \
		apt-get install -y nodejs && \
		echo "**** clean up ****" && \
		apt-get clean && \
		rm -rf \
		/config/* \
		/tmp/* \
		/var/lib/apt/lists/* \
		/var/tmp/*
# Install php 8.2 and composer
RUN \
	echo "**** install php 8.2 and composer ****" && \
		apt-get update && \
		apt-get install -y \
		php8.2 \
		php8.2-cli \
		php8.2-common \
		php8.2-curl \
		php8.2-fpm \
		php8.2-gd \
		php8.2-json \
		php8.2-mbstring \
		php8.2-mysql \
		php8.2-opcache \
		php8.2-readline \
		php8.2-xml \
		php8.2-zip && \
		curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php && \
		php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
		echo "**** clean up ****" && \
		apt-get clean && \
		rm -rf \
		/config/* \
		/tmp/* \
		/var/lib/apt/lists/* \
		/var/tmp/*

# add local files (get from original repo)
#COPY /root /
# https://github.com/linuxserver/docker-code-server/tree/master/root
RUN \
	git clone https://github.com/linuxserver/docker-code-server --depth 1 && \
	cp -r /docker-code-server/root/* / && \
	rm -rf /docker-code-server
	

# ports and volumes
EXPOSE 8443