name: Build Portainer image manually
on:
  workflow_dispatch:
    inputs:
      image:
        description: "Image to build"
        type: choice
        options:
          - "boringproxy"
          - "frp"
          - "code-server"
          - "code-server-canvas"
          - "php-fpm"
          - "bun"
          - "excalidraw"
          - "excalidraw-room"
        required: true
jobs:
  build:
    name: "Build image: ${{ github.event.inputs.image }}"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          image: tonistiigi/binfmt:qemu-v7.0.0-28
      # Setup buildx
      - uses: docker/setup-buildx-action@v2
        with:
          version: "latest"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./Portainer/${{ github.event.inputs.image }}
          file: ./Portainer/${{ github.event.inputs.image }}/dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/garycraft/${{ github.event.inputs.image }}:latest
